### ISSUE TITLE
lv4 과제 리뷰

### ISSUE THREAD

**Issue by Ho-yeong** [kme-developer/sparta-personal-23.07.10#2]
# 종합의견
- 전반적으로 깔끔하게 잘 작성해주셨습니다.
- 몇가지 실수말고는 크게 지적할 점이 없습니다.
- 이대로 lv5 ~ 최종 프로젝트까지 가보도록 합시다.

**Comment by Ho-yeong** [comment]
https://github.com/kme-developer/sparta-personal-23.07.10/blob/1b205cc20630174da69f4bcd3db40f8125fc0f4f/routes/commentsRoute.js#L24
이 경우 400 에러가 더 적절합니다.

https://github.com/kme-developer/sparta-personal-23.07.10/blob/1b205cc20630174da69f4bcd3db40f8125fc0f4f/routes/commentsRoute.js#L116-L119
try-catch문 안에서 한번 더 try-catch를 사용중이신데 이유가 있을까요?

**Comment by kme-developer** [comment]
첫번째 사항
: status code 400 => 412 / 지적해주신 내용 확인했습니다.
두번째 사항
: 이유가 있었던 것은 아니고 잘못 입력된 것 같습니다.

**Comment by kme-developer** [comment]
01
: status code 400 => 412 / 지적해주신 내용 확인했습니다.

02
: 이유가 있었던 것은 아니고 잘못 입력된 것 같습니다.

감사합니다!
